TARGET:=FANN-dyn
PLATFORM:=nsitexe_dr1000c

USER_BUILD:=pushd ..; ./install_FANN.sh; popd; pushd ../examples; ./build_runtest.sh; popd
USER_RUN:=pushd ../examples; ./run_runtest.sh; popd
OPTIMISTIC_ANALYSIS:=0
CANDIDATE_THRESHOLD:=50
FILTER_RATIO:=0.01
FIND_DLP:=1
FIND_PLP:=0
FIND_TLP:=0
FIND_OFL:=0
TRACE_REMOTELY:=0
VECTOR_CONTENTION:=0
BASEPATH:=.
PTHREADS_PROGRAM:=0
SCALAR_CONTENTION:=0
ENABLE_AUTO_VECTORIZATION:=0
USER_CLEAN:=pushd ../examples; ./clean_examples.sh; popd; pushd ..; ./uninstall_FANN.sh; popd
USER_SLX_MODE_SWITCH:=pushd ../examples; ./clean_examples.sh; popd; pushd ..; ./uninstall_FANN.sh; popd
USER_INIT:=
